#!/bin/bash

HEADER='<!--
    EasyAudit Premium - Magento 2 Audit Extension

    Copyright (c) 2025 Crealoz. All rights reserved.
    Licensed under the EasyAudit Premium EULA.

    This software is provided under a paid license and may not be redistributed,
    modified, or reverse-engineered without explicit permission.
    See EULA for details: https://crealoz.fr/easyaudit-eula
-->'

# Trouver tous les fichiers XML dans le répertoire courant et ses sous-dossiers
find . -type f -name "*.xml" 2>/dev/null | while read -r file; do
    if ! grep -q "EasyAudit Premium - Magento 2 Audit Extension" "$file"; then
        echo "Ajout de l'en-tête à : $file"
        awk -v header="$HEADER" 'NR==1 {print header "\n" $0; next} {print}' "$file" > temp_file && mv temp_file "$file"
    else
        echo "En-tête déjà présent dans : $file"
    fi
done

echo "✅ Ajout terminé."
